##################################################
##
## You're viewing a file in the SMAPI mod dump, which contains a copy of every open-source SMAPI mod
## for queries and analysis.
##
## This is *not* the original file, and not necessarily the latest version.
## Source repository: https://github.com/JoeStrout/Farmtronics
##
##################################################

name: Merge Dependabot PRs
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"

permissions:
  pull-requests: write
  contents: write
  checks: read

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: gh pr merge -s "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
