##################################################
##
## You're viewing a file in the SMAPI mod dump, which contains a copy of every open-source SMAPI mod
## for queries and analysis.
##
## This is *not* the original file, and not necessarily the latest version.
## Source repository: https://github.com/eideehi/EideeEasyFishing
##
##################################################

blank_issues_enabled: false
contact_links:
  - name: eidee.net - Discoed server
    url: https://discord.gg/DDQqxkK7s6
    about: Questions, suggestions, comments, etc. can be directed here.
