// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.onGameLaunched(System.Object,StardewModdingAPI.Events.GameLaunchedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.addConsoleCommands")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.cmdGrandpaScore(System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.cmdResetEvaluation(System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.grandpaEvaluations_Postfix(StardewValley.GameLocation,Microsoft.Xna.Framework.GameTime)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.UtilityPatches.getGrandpaScore_Postfix(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.UtilityPatches.getGrandpaCandlesFromScore_Postfix(System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.onButtonPressed(System.Object,StardewModdingAPI.Events.ButtonPressedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.farmCheckAction_Prefix(StardewValley.GameLocation,Microsoft.Xna.Framework.GameTime)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.farmCheckAction_Prefix(xTile.Dimensions.Location,xTile.Dimensions.Rectangle,StardewValley.Farmer,StardewValley.Farm)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.farmCheckAction_Prefix(xTile.Dimensions.Location,xTile.Dimensions.Rectangle,StardewValley.Farmer,StardewValley.Farm,System.Boolean@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.grandpa1CandleCallback(StardewValley.Item,StardewValley.Farmer)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.grandpa2CandleCallback(StardewValley.Item,StardewValley.Farmer)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.grandpa3CandleCallback(StardewValley.Item,StardewValley.Farmer)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.addGrandpaCandles_Prefix(StardewValley.Farm)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmerPatches.addItemsByMenuIfNecessary_Postfix")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.onSaveLoaded(System.Object,StardewModdingAPI.Events.SaveLoadedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.onDayStarted(System.Object,StardewModdingAPI.Events.DayStartedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.onUpdateTicked(System.Object,StardewModdingAPI.Events.UpdateTickedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.grandpaEvaluations_Postfix")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.grandpaEvaluations_Prefix")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.grandpaEvaluations_Postfix(StardewValley.GameLocation)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.grandpaEvaluations_Prefix(StardewValley.GameLocation)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.onWarped(System.Object,StardewModdingAPI.Events.WarpedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.resetEventsCacheIfYearChanged")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.skipEvent_Postfix")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ObjectPatches.checkForSpecialItemHoldUpMeessage_Postfix(System.String@,StardewValley.Object)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.skipEvent_Postfix(StardewValley.Event)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModConfig.setPortraitTokens")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.FarmPatches.grandpa4CandleCallback(StardewValley.Item,StardewValley.Farmer)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ConsoleCommands.cmdGrandpaConfig(System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ConsoleCommands.cmdGrandpaDebug(System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ConsoleCommands.cmdGrandpaScore(System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ConsoleCommands.cmdResetEvaluation(System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.EventPatches.grandpaEvaluations_Postfix(StardewValley.Event)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ItemGrabMenuPatches.receiveLeftClick_Transpiler(System.Collections.Generic.IEnumerable{Harmony.CodeInstruction})~System.Collections.Generic.IEnumerable{Harmony.CodeInstruction}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.cmdGrandpaConfig(System.String,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:AngryGrandpa.ModEntry.cmdGrandpaDebug(System.String,System.String[])")]
