[Config]
ConfigVersion = "0.13.0.102"
Enabled = true
ToggleButton = "F11"
PreferredMaxTextureDimension = 16384
ShowIntroMessage = false
DataStoreOverride = ""

[Config.WatchDog]
Enabled = false
DefaultSleepInterval = 5000
ShortSleepInterval = 500
InterruptInterval = 10000

[Config.Garbage]
CollectAccountUnownedTextures = false
CollectAccountOwnedTextures = false
RequiredFreeMemory = 64
RequiredFreeMemoryHysterisis = 1.5
SeasonalPurge = true
LatencyMode = "SustainedLowLatency"

[Config.Debug.Logging]
LogLevel = "Trace"

[Config.DrawState]
SetLinear = true
MSAASamples = 0
DisableDepthBuffer = false
BackbufferFormat = "Color"

[Config.Performance]
TransientGCTickCount = 150

[Config.Resample]
Enabled = true
Scale = true
AssumeGammaCorrected = false
TrimWater = true
ScaleBias = 0.1000000014901161
MaxScale = 4294967295
MinimumTextureDimensions = 1
EnableWrappedAddressing = false
UseFrametimeStalling = true
UseColorEnhancement = true
PremultipliedAlphaThreshold = 1
PremultiplyAlpha = true
PremultiplyAlphaAssume = true
SlicedTextures = [
	"LooseSprites\\Cursors::0,2000:640,256", 
	"LooseSprites\\Cloudy_Ocean_BG", 
	"LooseSprites\\Cloudy_Ocean_BG_Night", 
	"LooseSprites\\stardewPanorama", 
	"Maps\\nightSceneMaru", 
	"Maps\\nightSceneMaruTrees", 
	"Maps\\sebastianMountainTiles", 
	"Maps\\sebastianRideTiles", 
	"Tilesheets\\GuntherExpedition2_Shadows", 
	"Tilesheets\\Highlands_Fog", 
	"Tilesheets\\Highlands_FogBackground"
]
TwoXTextures = [
	"Maps\\WoodBuildings"
]
FourXTextures = [
	"Characters\\Monsters\\Crow", 
	"Characters\\femaleRival", 
	"Characters\\maleRival", 
	"LooseSprites\\Bat", 
	"LooseSprites\\buildingPlacementTiles", 
	"LooseSprites\\chatBox", 
	"LooseSprites\\daybg", 
	"LooseSprites\\DialogBoxGreen", 
	"LooseSprites\\hoverBox", 
	"LooseSprites\\nightbg", 
	"LooseSprites\\robinAtWork", 
	"LooseSprites\\skillTitles", 
	"LooseSprites\\textBox", 
	"Maps\\busPeople", 
	"Maps\\cavedarker", 
	"Maps\\FarmhouseTiles", 
	"Maps\\GreenHouseInterior", 
	"Maps\\MenuTiles", 
	"Maps\\MenuTilesUncolored", 
	"Maps\\spring_BusStop", 
	"Maps\\TownIndoors", 
	"TerrainFeatures\\BuffsIcons", 
	"TerrainFeatures\\DiggableWall_basic", 
	"TerrainFeatures\\DiggableWall_basic_dark", 
	"TerrainFeatures\\DiggableWall_frost", 
	"TerrainFeatures\\DiggableWall_frost_dark", 
	"TerrainFeatures\\DiggableWall_lava", 
	"TerrainFeatures\\DiggableWall_lava_dark", 
	"TerrainFeatures\\Stalagmite", 
	"TerrainFeatures\\Stalagmite_Frost", 
	"TerrainFeatures\\Stalagmite_Lava", 
	"TileSheets\\Fireball", 
	"TileSheets\\rain", 
	"TileSheets\\animations"
]
Blacklist = [
	"LooseSprites\\Lighting\\", 
	"@^Maps\\\\.+Mist", 
	"@^Maps\\\\.+mist", 
	"@^Maps\\\\.+Shadow", 
	"@^Maps\\\\.+Shadows", 
	"@^Maps\\\\.+Fog", 
	"@^Maps\\\\.+FogBackground"
]

[Config.Resample.BlockMultipleAnalysis]
Enabled = true
EqualityThreshold = 1
MaxInequality = 1

[Config.Resample.BlockCompression]
Enabled = true
Quality = "Highest"
HardAlphaDeviationThreshold = 7

[Config.Resample.Padding]
Enabled = true
MinimumSizeTexels = 4
IgnoreUnknown = false
PadSolidEdges = false
StrictList = [
	"LooseSprites\\Cursors"
]
AlwaysList = [
	"LooseSprites\\font_bold", 
	"Characters\\Farmer\\hairstyles", 
	"Characters\\Farmer\\hairstyles2", 
	"Characters\\Farmer\\hats", 
	"Characters\\Farmer\\pants", 
	"Characters\\Farmer\\shirts", 
	"TileSheets\\weapons", 
	"TileSheets\\bushes", 
	"TerrainFeatures\\grass", 
	"TileSheets\\debris", 
	"TileSheets\\animations", 
	"Maps\\springobjects", 
	"Maps\\summerobjects", 
	"Maps\\winterobjects", 
	"Maps\\fallobjects", 
	"Buildings\\houses", 
	"TileSheets\\furniture", 
	"TerrainFeatures\\tree1_spring", 
	"TerrainFeatures\\tree2_spring", 
	"TerrainFeatures\\tree3_spring", 
	"TerrainFeatures\\tree1_summer", 
	"TerrainFeatures\\tree2_summer", 
	"TerrainFeatures\\tree3_summer", 
	"TerrainFeatures\\tree1_fall", 
	"TerrainFeatures\\tree2_fall", 
	"TerrainFeatures\\tree3_fall", 
	"TerrainFeatures\\tree1_winter", 
	"TerrainFeatures\\tree2_winter", 
	"TerrainFeatures\\tree3_winter"
]

[Config.Resample.xBRZ]
LuminanceWeight = 1
EqualColorTolerance = 20
DominantDirectionThreshold = 4.4
SteepDirectionThreshold = 2.2
CenterDirectionBias = 3
UseGradientBlockCopy = false

[Config.WrapDetection]
edgeThreshold = 0.2000000029802322
alphaThreshold = 1

[Config.AsyncScaling]
EnabledForUnknownTextures = true
ForceSynchronousStores = true
ThrottledSynchronousLoads = true
CanFetchAndLoadSameFrame = true

[Config.MemoryCache]
Enabled = true
AlwaysFlush = false

[Config.SuspendedCache]
Enabled = true

[Config.SMAPI]
TextureCacheEnabled = true
TextureCacheHighMemoryEnabled = false
ApplyPatchEnabled = true
ApplyPatchUseCache = true
ApplyPatchPinMemory = false

[Config.Extras]
FastQuit = true
SmoothLines = true
OptimizeWarpPoints = true
TrueShortestPath = false
AllowNPCsOnFarm = false
StableSort = true
PreventUnresponsive = true
OptimizeEngineTaskRunner = true

[Config.Extras.Snow]
Enabled = true
MinimumDensity = 1024
MaximumDensity = 3072
MaximumRotationSpeed = 0.01666666666666667
MaximumScale = 3
PuffersnowChance = -1

[Config.Extras.ModPatches]
PatchCustomNPCFixes = false

[Config.FileCache]
Enabled = true
Compress = "Zstd"
ForceCompress = false
PreferSystemCompression = false
