namespace Hello_SMAPI.Framework
{
    class ModConfig
    {
        public string[] Responses { get; set; } = new string[] {
            "An honor to speak to you",
            "All hail the master",
            "Be quiet",
            "Bruh, shut up",
            "Bye",
            "Error: Please upload your smapi log to https://log.smapi.io and share the link on the stardew valley discord :) (no joke btw :)))))) )",
            "Go away",
            "Good day",
            "Good afternoon",
            "Good evening",
            "Good morning",
            "Good night",
            "Go play stupid, I'm just overlooking the smapi log",
            "Greetings",
            "Hallo",
            "Hell",
            "Hell - wait a minute, how am I talking to you...? Goodbye",
            "Hell no...",
            "Hello",
            "Hello",
            "Hello",
            "Hello",
            "Hello my beautiful princess",
            "Hello my handsome prince",
            "Hello my prince",
            "Hello my princess",
            "Hello player",
            "Hey",
            "Heyo",
            "Hey there",
            "Hi",
            "Hi",
            "Hi",
            "Hi im dad",
            "Hi I am SMAPI and you are wasting your time",
            "k stop saying hello",
            "Howdy",
            "How's life?",
            "I don't know you",
            "* [ignores player]",
            "I'm not suppose to speak to you about this",
            "<insert greeting here>",
            "heh... Hello *[laughs menacingly]",
            "Morning",
            "My face is too tired to speak to you.",
            "Nice to meet you",
            "No u",
            "Peace out, I have better things to do",
            "* [plays dead]",
            "* [pufferchick noises]",
            "reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
            "shhhhhhhh!",
            "* [shhhhhhhh! SMAPI has spotted an XNB mod in its natural habitat...] \"RELOADING\"",
            "Shutting down...",
            "* [SMAPI disliked that...]",
            "Stop annoying me",
            "sup",
            "What's up",
            "Who wasted their time making this mod...",
            "Why?!",
            "Why did you install this mod? Now I have to greet you every time... ugh...",
            "Yo"
        };
    }
}
