/*************************************************
**
** You're viewing a file in the SMAPI mod dump, which contains a copy of every open-source SMAPI mod
** for queries and analysis.
**
** This is *not* the original file, and not necessarily the latest version.
** Source repository: https://github.com/Esca-MMC/FarmTypeManager
**
*************************************************/

using HarmonyLib;
using StardewModdingAPI;
using StardewValley;
using StardewValley.Menus;
using System;

namespace FarmTypeManager
{
    public partial class ModEntry : Mod
    {
        /// <summary>A Harmony patch that adds spawned minerals to the player's collection menu when picked up.</summary>
        public class HarmonyPatch_AddSpawnedMineralsToCollections
        {
            /// <summary>Applies this Harmony patch to the game through the provided instance.</summary>
            /// <param name="harmony">This mod's Harmony instance.</param>
            public static void ApplyPatch(Harmony harmony)
            {
                Utility.Monitor.Log($"Applying Harmony patch \"{nameof(HarmonyPatch_AddSpawnedMineralsToCollections)}\": prefixing SDV method \"Farmer.addItemToInventoryBool(Item, bool)\".", LogLevel.Trace);
                harmony.Patch(
                    original: AccessTools.Method(typeof(Farmer), nameof(Farmer.addItemToInventoryBool), new[] { typeof(Item), typeof(bool) }),
                    prefix: new HarmonyMethod(typeof(HarmonyPatch_AddSpawnedMineralsToCollections), nameof(addItemToInventoryBool_Prefix))
                );
            }

            /// <summary>Updates the local player's collection menu when they pick up a new mineral.</summary>
            /// <remarks>
            /// This method imitates the check performed in the original, but targets minerals instead of gems.
            /// As of SDV 1.4.5, the original code only adds minerals to players' collections when the minerals are generated by the <see cref="GeodeMenu"/>.
            /// </remarks>
            /// <param name="item">The item being picked up. This may be null in some contexts.</param>
            /// <param name="makeActiveObject">A boolean flag ignored by this patch method.</param>
            /// <param name="__instance">The Farmer picking up the item.</param>
            public static void addItemToInventoryBool_Prefix(Item item, bool makeActiveObject, Farmer __instance)
            {
                try
                {
                    if (__instance.IsLocalPlayer && item != null) //if this farmer is the local player and the item isn't null
                    {
                        if (!(Game1.activeClickableMenu is GeodeMenu)) //if the active menu is NOT a geode menu (which already handles this process)
                        {
                            if (!item.HasBeenInInventory && item is StardewValley.Object obj && !obj.HasBeenPickedUpByFarmer) //if this item is an object that has NOT been picked up before
                            {
                                if (obj.Category == -12) //if this object is in the "minerals" category
                                {
                                    __instance.foundMineral(obj.ParentSheetIndex); //add this mineral to the player's collection
                                }
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    Utility.Monitor.LogOnce("A Harmony patch encountered an error. Minerals spawned by this mod might not be added to your collection menu when picked up. The auto-generated error message is displayed below:\n" +
                        "----------\n" +
                        ex.ToString(), LogLevel.Warn);
                }
            }
        }
    }
}
