namespace Randomizer
{
	/// <summary>
	/// An enum containing all the weapon indexes
	/// </summary>
	public enum WeaponIndexes
	{
		RustySword = 0,
		SilverSaber,
		DarkSword,
		HolyBlade,
		GalaxySword,
		BoneSword,
		IronEdge,
		TemplarsBlade,
		ObsidianEdge,
		LavaKatana,
		Claymore,
		SteelSmallsword,
		WoodenBlade,
		InsectHead,
		NeptunesGlaive,
		ForestSword,
		CarvingKnife,
		IronDirk,
		BurglarsShank,
		ShadowDagger,
		ElfBlade,
		CrystalDagger,
		WindSpire,
		GalaxyDagger,
		WoodClub,
		AlexsBat,
		LeadRod,
		WoodMallet,
		TheSlammer,
		GalaxyHammer,
		SamsOldGuitar,
		Femur,
		Slingshot,
		MasterSlingshot,
		GalaxySlingshot,
		ElliottsPencil,
		MarusWrench,
		HarveysMallet,
		PennysFryer,
		LeahsWhittler,
		AbbysPlanchette,
		SebsLostMace,
		HaleysIron,
		PiratesSword,
		Cutlass,
		WickedKris,
		Kudgel,
		Scythe,
		YetiTooth,
		Rapier,
		SteelFalchion,
		BrokenTrident,
		TemperedBroadsword,
		GoldenScythe
	}
}