/*************************************************
**
** You're viewing a file in the SMAPI mod dump, which contains a copy of every open-source SMAPI mod
** for queries and analysis.
**
** This is *not* the original file, and not necessarily the latest version.
** Source repository: https://github.com/paritee/Paritee.StardewValley.Frameworks
**
*************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterFarmAnimalVariety.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/5927/11343/1500/White Cow,Brown Cow/Barn,Big Barn,Deluxe Barn")]
        public string FarmAnimals_DairyCow {
            get {
                return ((string)(this["FarmAnimals_DairyCow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0/5922/11334/800/White Chicken,Brown Chicken,Blue Chicken,Void Chicken/Coop,Big C" +
            "oop,Deluxe Coop")]
        public string FarmAnimals_Chicken {
            get {
                return ((string)(this["FarmAnimals_Chicken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4/5942/11352/8000/Sheep/Deluxe Barn")]
        public string FarmAnimals_Sheep {
            get {
                return ((string)(this["FarmAnimals_Sheep"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2/5933/11349/4000/Goat/Big Barn,Deluxe Barn")]
        public string FarmAnimals_Goat {
            get {
                return ((string)(this["FarmAnimals_Goat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6/5948/11346/16000/Pig/Deluxe Barn")]
        public string FarmAnimals_Pig {
            get {
                return ((string)(this["FarmAnimals_Pig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3/5937/11337/4000/Duck/Big Coop,Deluxe Coop")]
        public string FarmAnimals_Duck {
            get {
                return ((string)(this["FarmAnimals_Duck"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5/5945/11340/8000/Rabbit/Deluxe Coop")]
        public string FarmAnimals_Rabbit {
            get {
                return ((string)(this["FarmAnimals_Rabbit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7/null/null/null/Dinosaur/Big Coop,Deluxe Coop")]
        public string FarmAnimals_Dinosaur {
            get {
                return ((string)(this["FarmAnimals_Dinosaur"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("assets")]
        public string AssetsDirectory {
            get {
                return ((string)(this["AssetsDirectory"]));
            }
        }
    }
}
