using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClimatesOfFerngillRebuild.Weathers
{
    enum WeatherTypes
    {
        None = CurrentWeather.Unset,
        Sunny = CurrentWeather.Sunny,
        Rainy = CurrentWeather.Rain,
        Snowy = CurrentWeather.Snow,
        Windy = CurrentWeather.Wind,
        Festival = CurrentWeather.Festival,
        Wedding = CurrentWeather.Wedding,
        Stormy = CurrentWeather.Rain | CurrentWeather.Lightning,
        Sunshower = CurrentWeather.Sunny | CurrentWeather.Rain,
        DryLightning = CurrentWeather.Sunny | CurrentWeather.Lightning,
        Blizzard = CurrentWeather.Blizzard | CurrentWeather.Snow,
        WhiteOut = CurrentWeather.WhiteOut | Blizzard,
        Fog = CurrentWeather.Fog | Sunny,
        RainyFog = CurrentWeather.Fog | Rainy,
        SnowyFog = CurrentWeather.Fog | Snowy,
        StormyFog = CurrentWeather.Fog | Stormy,
        DryLightningFog = CurrentWeather.Fog | DryLightning,
        SunshowerFog = CurrentWeather.Fog | Sunshower,
        BlizzardFog = CurrentWeather.Fog | Blizzard,
        WhiteOutFog = CurrentWeather.Fog | WhiteOut,
        BloodRain = CurrentWeather.BloodMoon | CurrentWeather.Rain,
        BloodSnow = CurrentWeather.BloodMoon | CurrentWeather.Snow,
        BloodStorm = CurrentWeather.BloodMoon | Stormy,
        BloodMoon = CurrentWeather.BloodMoon | CurrentWeather.Sunny,
        BloodWind = CurrentWeather.BloodMoon | CurrentWeather.Wind,
        BloodFog = CurrentWeather.BloodMoon | Fog,
        BloodRainFog = CurrentWeather.BloodMoon | RainyFog,
        BloodSnowFog = CurrentWeather.BloodMoon | SnowyFog,
        BloodStormFog = CurrentWeather.BloodMoon | StormyFog,
        BloodDryLightFog = CurrentWeather.BloodMoon | DryLightningFog,
        ThunderFrenzy = CurrentWeather.ThunderFrenzy | Stormy,
        ThunderFrenzyFog = ThunderFrenzy | CurrentWeather.Fog,
        HurricaneRain = Rainy | CurrentWeather.HurricaneRain,
        HurricaneRainFog = HurricaneRain | CurrentWeather.Fog,
        HurricaneThunder = HurricaneRain | ThunderFrenzy,
        HurricaneThunderFog = HurricaneThunder | CurrentWeather.Fog,
        SunnyHeatwave = CurrentWeather.Sunny | CurrentWeather.Heatwave,
        RainyHeatwave = CurrentWeather.Rain | CurrentWeather.Heatwave,
        SnowyHeatwave = CurrentWeather.Snow | CurrentWeather.Heatwave,
        WindyHeatwave = CurrentWeather.Wind | CurrentWeather.Heatwave,
        FestivalHeatwave = CurrentWeather.Festival | CurrentWeather.Heatwave,
        WeddingHeatwave = CurrentWeather.Wedding | CurrentWeather.Heatwave,
        StormyHeatwave = CurrentWeather.Rain | CurrentWeather.Lightning | CurrentWeather.Heatwave,
        SunshowerHeatwave = CurrentWeather.Sunny | CurrentWeather.Rain | CurrentWeather.Heatwave,
        DryLightningHeatwave = CurrentWeather.Sunny | CurrentWeather.Lightning | CurrentWeather.Heatwave,
        BlizzardHeatwave = CurrentWeather.Blizzard | CurrentWeather.Snow | CurrentWeather.Heatwave,
        WhiteOutHeatwave = CurrentWeather.WhiteOut | Blizzard | CurrentWeather.Heatwave,
        FogHeatwave = CurrentWeather.Fog | Sunny | CurrentWeather.Heatwave,
        RainyFogHeatwave = CurrentWeather.Fog | Rainy | CurrentWeather.Heatwave,
        SnowyFogHeatwave = CurrentWeather.Fog | Snowy | CurrentWeather.Heatwave,
        StormyFogHeatwave = CurrentWeather.Fog | Stormy | CurrentWeather.Heatwave,
        DryLightningFogHeatwave = CurrentWeather.Fog | DryLightning | CurrentWeather.Heatwave,
        SunshowerFogHeatwave = CurrentWeather.Fog | Sunshower | CurrentWeather.Heatwave,
        BlizzardFogHeatwave = CurrentWeather.Fog | Blizzard | CurrentWeather.Heatwave,
        WhiteOutFogHeatwave = CurrentWeather.Fog | WhiteOut | CurrentWeather.Heatwave,
        BloodRainHeatwave = CurrentWeather.BloodMoon | CurrentWeather.Rain | CurrentWeather.Heatwave,
        BloodSnowHeatwave = CurrentWeather.BloodMoon | CurrentWeather.Snow | CurrentWeather.Heatwave,
        BloodStormHeatwave = CurrentWeather.BloodMoon | Stormy | CurrentWeather.Heatwave,
        BloodMoonHeatwave = CurrentWeather.BloodMoon | CurrentWeather.Sunny | CurrentWeather.Heatwave,
        BloodWindHeatwave = CurrentWeather.BloodMoon | CurrentWeather.Wind | CurrentWeather.Heatwave,
        BloodFogHeatwave = CurrentWeather.BloodMoon | Fog | CurrentWeather.Heatwave,
        BloodRainFogHeatwave = CurrentWeather.BloodMoon | RainyFog | CurrentWeather.Heatwave,
        BloodSnowFogHeatwave = CurrentWeather.BloodMoon | SnowyFog | CurrentWeather.Heatwave,
        BloodStormFogHeatwave = CurrentWeather.BloodMoon | StormyFog | CurrentWeather.Heatwave,
        BloodDryLightFogHeatwave = CurrentWeather.BloodMoon | DryLightningFog | CurrentWeather.Heatwave,
        ThunderFrenzyHeatwave = CurrentWeather.ThunderFrenzy | Stormy | CurrentWeather.Heatwave,
        ThunderFrenzyFogHeatwave = ThunderFrenzy | CurrentWeather.Fog | CurrentWeather.Heatwave,
        HurricaneRainHeatwave = Rainy | CurrentWeather.HurricaneRain | CurrentWeather.Heatwave,
        HurricaneRainFogHeatwave = HurricaneRain | CurrentWeather.Fog | CurrentWeather.Heatwave,
        HurricaneThunderHeatwave = HurricaneRain | ThunderFrenzy | CurrentWeather.Heatwave,
        HurricaneThunderFogHeatwave = HurricaneThunder | CurrentWeather.Fog | CurrentWeather.Heatwave,
        SunnyFrost = CurrentWeather.Sunny | CurrentWeather.Frost,
        RainyFrost = CurrentWeather.Rain | CurrentWeather.Frost,
        SnowyFrost = CurrentWeather.Snow | CurrentWeather.Frost,
        WindyFrost = CurrentWeather.Wind | CurrentWeather.Frost,
        FestivalFrost = CurrentWeather.Festival | CurrentWeather.Frost,
        WeddingFrost = CurrentWeather.Wedding | CurrentWeather.Frost,
        StormyFrost = CurrentWeather.Rain | CurrentWeather.Lightning | CurrentWeather.Frost,
        SunshowerFrost = CurrentWeather.Sunny | CurrentWeather.Rain | CurrentWeather.Frost,
        DryLightningFrost = CurrentWeather.Sunny | CurrentWeather.Lightning | CurrentWeather.Frost,
        BlizzardFrost = CurrentWeather.Blizzard | CurrentWeather.Snow | CurrentWeather.Frost,
        WhiteOutFrost = CurrentWeather.WhiteOut | Blizzard | CurrentWeather.Frost,
        FogFrost = CurrentWeather.Fog | Sunny | CurrentWeather.Frost,
        RainyFogFrost = CurrentWeather.Fog | Rainy | CurrentWeather.Frost,
        SnowyFogFrost = CurrentWeather.Fog | Snowy | CurrentWeather.Frost,
        StormyFogFrost = CurrentWeather.Fog | Stormy | CurrentWeather.Frost,
        DryLightningFogFrost = CurrentWeather.Fog | DryLightning | CurrentWeather.Frost,
        SunshowerFogFrost = CurrentWeather.Fog | Sunshower | CurrentWeather.Frost,
        BlizzardFogFrost = CurrentWeather.Fog | Blizzard | CurrentWeather.Frost,
        WhiteOutFogFrost = CurrentWeather.Fog | WhiteOut | CurrentWeather.Frost,
        BloodRainFrost = CurrentWeather.BloodMoon | CurrentWeather.Rain | CurrentWeather.Frost,
        BloodSnowFrost = CurrentWeather.BloodMoon | CurrentWeather.Snow | CurrentWeather.Frost,
        BloodStormFrost = CurrentWeather.BloodMoon | Stormy | CurrentWeather.Frost,
        BloodMoonFrost = CurrentWeather.BloodMoon | CurrentWeather.Sunny | CurrentWeather.Frost,
        BloodWindFrost = CurrentWeather.BloodMoon | CurrentWeather.Wind | CurrentWeather.Frost,
        BloodFogFrost = CurrentWeather.BloodMoon | Fog | CurrentWeather.Frost,
        BloodRainFogFrost = CurrentWeather.BloodMoon | RainyFog | CurrentWeather.Frost,
        BloodSnowFogFrost = CurrentWeather.BloodMoon | SnowyFog | CurrentWeather.Frost,
        BloodStormFogFrost = CurrentWeather.BloodMoon | StormyFog | CurrentWeather.Frost,
        BloodDryLightFogFrost = CurrentWeather.BloodMoon | DryLightningFog | CurrentWeather.Frost,
        ThunderFrenzyFrost = CurrentWeather.ThunderFrenzy | Stormy | CurrentWeather.Frost,
        ThunderFrenzyFogFrost = ThunderFrenzy | CurrentWeather.Fog | CurrentWeather.Frost,
        HurricaneRainFrost = Rainy | CurrentWeather.HurricaneRain | CurrentWeather.Frost,
        HurricaneRainFogFrost = HurricaneRain | CurrentWeather.Fog | CurrentWeather.Frost,
        HurricaneThunderFrost = HurricaneRain | ThunderFrenzy | CurrentWeather.Frost,
        HurricaneThunderFogFrost = HurricaneThunder | CurrentWeather.Fog | CurrentWeather.Frost
    }
}