import constants

npcs = {
    'abigail': constants.ABIGAIL,
    'alex': constants.ALEX,
    'birdie': constants.BIRDIE,
    '[the] bouncer': constants.BOUNCER,
    'caroline': constants.CAROLINE,
    'clint': constants.CLINT,
    'demetrius': constants.DEMETRIUS,
    '[the] dwarf': constants.DWARF,
    'elliott': constants.ELLIOTT,
    'emily': constants.EMILY,
    'evelyn': constants.EVELYN,
    'george': constants.GEORGE,
    'gil': constants.GIL,
    '[the] governor': constants.GOVERNOR,
    'grandpa': constants.GRANDPA,
    'gunther': constants.GUNTHER,
    'gus': constants.GUS,
    'haley': constants.HALEY,
    'harvey': constants.HARVEY,
    'jas': constants.JAS,
    'jodi': constants.JODI,
    'kent': constants.KENT,
    'krobus': constants.KROBUS,
    'leah': constants.LEAH,
    'leo': constants.LEO,
    '[mayor] lewis': constants.LEWIS,
    'linus': constants.LINUS,
    'marlon': constants.MARLON,
    'marnie': constants.MARNIE,
    '(muh roo | mar oo)': constants.MARU,
    'morris': constants.MORRIS,
    'mister (kwee | key)': constants.MR_QI,
    'pam': constants.PAM,
    'penny': constants.PENNY,
    'pierre': constants.PIERRE,
    'professor snail': constants.PROFESSOR_SNAIL,
    'robin': constants.ROBIN,
    'sam': constants.SAM,
    'sandy': constants.SANDY,
    'sebastian': constants.SEBASTIAN,
    'shane': constants.SHANE,
    'vincent': constants.VINCENT,
    'willy': constants.WILLY,
    '[the] wizard': constants.WIZARD,
}