import dragonfly as df
import constants

class Item:

    def __init__(self, name: str, commands=None):
        self.name = name
        if commands is None:
            self.commands = self.commands_from_name(name)
        else:
            self.commands = commands

    def commands_from_name(self, name: str):
        # 'Wood Fence' -> ['wood fence']
        return [name.lower()]

craftable_items = (
    Item("Ancient Seeds"),
    Item("Bait"),
    Item("Barbed Hook"),
    Item("Barrel Brazier"),
    Item("Basic Retaining Soil"),
    Item("Basic Fertilizer"),
    Item("Bee House"),
    Item("Bomb"),
    Item("Bone Mill"),
    Item("Brick Floor"),
    Item("Bug Steak"),
    Item("Campfire"),
    Item("Carved Brazier"),
    Item("Cask"),
    Item("Charcoal Kiln"),
    Item("Cheese Press"),
    Item("Cherry Bomb"),
    Item("Chest"),
    Item("Cobblestone Path"),
    Item("Cookout Kit"),
    Item("Cork Bobber"),
    Item("Crab Pot"),
    Item("Crystalarium"),
    Item("Crystal Floor"),
    Item("Crystal Path"),
    Item("Dark Sign"),
    Item("Deluxe Fertilizer"),
    Item("Deluxe Retaining Soil"),
    Item("Deluxe Scarecrow"),
    Item("Deluxe Speed-Gro", ["deluxe speed grow"]),
    Item("Dressed Spinner"),
    Item("Drum Block"),
    Item("Explosive Ammo"),
    Item("Fairy Dust"),
    Item("Farm Computer"),
    Item("Fiber Seeds"),
    Item("Field Snack"),
    Item("Flute Block"),
    Item("Garden Pot"),
    Item("Geode Crusher"),
    Item("Glowstone Ring"),
    Item("Gold Bar"),
    Item("Gold Brazier"),
    Item("Grass Starter"),
    Item("Gravel Path"),
    Item("Hardwood Fence"),
    Item("Hopper"),
    Item("Heavy Tapper"),
    Item("Hyper Speed-Gro", ["hyper speed grow"]),
    Item("Iridium Band"),
    Item("Iridium Sprinkler"),
    Item("Iron Bar"),
    Item("Iron Fence"),
    Item("Iron Lamp-post"),
    Item("Jack-O-Lantern", ["jack-o-lantern"]),
    Item("Keg"),
    Item("Life Elixir"),
    Item("Lightning Rod"),
    Item("Loom"),
    Item("Magic Bait"),
    Item("Magnet"),
    Item("Marble Brazier"),
    Item("Mayonnaise Machine"),
    Item("Mega Bomb"),
    Item("Mini-Jukebox", ["mini jukebox"]),
    Item("Mini-Obelisk", ["mini obelisk"]),
    Item("Monster Musk"),
    Item("Oil Maker"),
    Item("Oil Of Garlic"),
    Item("Ostrich Incubator"),
    Item("Quality Bobber"),
    Item("Quality Fertilizer"),
    Item("Quality Retaining Soil"),
    Item("Quality Sprinkler"),
    Item("Preserves Jar"),
    Item("Rain Totem"),
    Item("Recycling Machine"),
    Item("Ring of Yoba"),
    Item("Rustic Plank Floor"),
    Item("Scarecrow"),
    Item("Seed Maker"),
    Item("Skull Brazier"),
    Item("Slime Egg-Press", ["slime egg press"]),
    Item("Slime Incubator"),
    Item("Solar Panel"),
    Item("Speed-Gro", ["speed grow"]),
    Item("Spinner"),
    Item("Sprinkler"),
    Item("Staircase"),
    Item("Stepping Stone Path"),
    Item("Stone Brazier"),
    Item("Stone Chest"),
    Item("Stone Fence"),
    Item("Stone Floor"),
    Item("Stone Walkway Floor"),
    Item("Stone Sign"),
    Item("Straw Floor"),
    Item("Stump Brazier"),
    Item("Sturdy Ring"),
    Item("Tapper"),
    Item("Tea Sapling"),
    Item("Thorns Ring"),
    Item("Torch"),
    Item("Trap Bobber"),
    Item("Treasure Hunter"),
    Item("Tree Fertilizer"),
    Item("Tub o' Flowers", ["tub [of | o] flowers"]),
    Item("Warp Totem Beach", ["warp totem beach", "beach warp totem"]),
    Item("Warp Totem Farm", ["warp totem farm", "farm warp totem"]),
    Item("Warp Totem Island", ["warp totem island", "island warp totem"]),
    Item("Warp Totem Mountains", ["warp totem mountains", "mountains warp totem"]),
    Item("Warrior Ring"),
    Item("Weathered Floor"),
    Item("Wicked Statue"),
    Item("Wild Bait"),
    Item("Wild Seeds (Fa)", ["fall wild seeds", "wild fall seeds", "wild seeds fall"]),
    Item("Wild Seeds (Sp)", ["spring wild seeds", "wild spring seeds", "wild seeds spring"]),
    Item("Wild Seeds (Su)", ["summer wild seeds", "wild summer seeds", "wild seeds summer"]),
    Item("Wild Seeds (Wi)", ["winter wild seeds", "wild winter seeds", "wild seeds winter"]),
    Item("Worm Bin"),
    Item("Wood Fence"),
    Item("Wood Floor"),
    Item("Wood Lamp-post"),
    Item("Wood Path"),
    Item("Wood Sign"),
    Item("Wooden Brazier"),
)

tools = (
    Item(constants.AXE),
    Item(constants.FISHING_ROD, ["fishing (rod | pole)"]),
    Item(constants.HOE),
    Item(constants.PICKAXE),
    Item(constants.SCYTHE),
    Item(constants.WATERING_CAN),
    Item(constants.SHEARS),
    Item(constants.MILK_PAIL),
    Item(constants.PAN),
)

other_items = (
    Item("Small Glow Ring"),
    Item("Glow Ring"),
    Item("Small Magnet Ring"),
    Item("Magnet Ring"),
    Item("Slime Charmer Ring"),
    Item("Vampire Ring"),
    Item("Savage Ring"),
    Item("Yoba Ring"),
    Item("Sturdy Ring"),
    Item("Burglars Ring"),
    Item("Iridium Band"),
    Item("Jukebox Ring"),
    Item("Amethyst Ring"),
    Item("Topaz Ring"),
    Item("Aquamarine Ring"),
    Item("Jade Ring"),
    Item("Emerald Ring"),
    Item("Ruby Ring"),
    Item("Cowboy Hat"),
    Item("Bowler Hat"),
    Item("Top Hat"),
    Item("Sombrero"),
    Item("Straw Hat"),
    Item("Official Cap"),
    Item("Blue Bonnet"),
    Item("Plum Chapeau"),
    Item("Skeleton Mask"),
    Item("Goblin Mask"),
    Item("Chicken Mask"),
    Item("Earmuffs"),
    Item("Delicate Bow"),
    Item("Tropiclip"),
    Item("Butterfly Bow"),
    Item("Hunters Cap"),
    Item("Trucker Hast"),
    Item("Sailors Cap"),
    Item("Good Ol Cap"),
    Item("Fedora"),
    Item("Cool Cap"),
    Item("Lucky Bow"),
    Item("Polka Bow"),
    Item("Gnomes Cap"),
    Item("Eye Patch"),
    Item("Santa Hat"),
    Item("Tiara"),
    Item("Hard Hat"),
    Item("Souwester"),
    Item("Daisy"),
    Item("Watermelon Band"),
    Item("Mouse Ears"),
    Item("Cat Ears"),
    Item("Cowgal Hat"),
    Item("Cowpoke Hat"),
    Item("Archers Cap"),
    Item("Panda Hat"),
    Item("Blue Cowboy Hat"),
    Item("Red Cowboy Hat"),
    Item("Cone Hat"),
    Item("Sneakers"),
    Item("Rubber Boots"),
    Item("Leather Boots"),
    Item("Work Boots"),
    Item("Combat Boots"),
    Item("Tundra Boots"),
    Item("Thermal Boots"),
    Item("Dark Boots"),
    Item("Firewalker Boots"),
    Item("Genie Shoes"),
    Item("Space Boots"),
    Item("Cowboy Boots"),
    Item("House Plant"),
    Item("Keg"),
    Item("Furnace"),
    Item("Table Piece Left"),
    Item("Table Piece Right"),
    Item("Mayonnaise Machine"),
    Item("Seed Maker"),
    Item("Wood Chair"),
    Item("Skeleton Model"),
    Item("Obelisk"),
    Item("Chicken Statue"),
    Item("Stone Cairn"),
    Item("Suit Of Armor"),
    Item("Sign Of The Vessel"),
    Item("Basic Log"),
    Item("Lawn Flamingo"),
    Item("Big Green Cane"),
    Item("Green Canes"),
    Item("Mixed Cane"),
    Item("Red Canes"),
    Item("Big Red Cane"),
    Item("Ornamental Hay Bale"),
    Item("Log Section"),
    Item("Grave Stone"),
    Item("Seasonal Decor"),
    Item("Stone Frog"),
    Item("Stone Parrot"),
    Item("Stone Owl"),
    Item("Stone Junimo"),
    Item("Slime Ball"),
    Item("Garden Pot"),
    Item("Bookcase"),
    Item("Fancy Table"),
    Item("Ancient Table"),
    Item("Ancient Stool"),
    Item("Grandfather Clock"),
    Item("Teddy Timer"),
    Item("Dead Tree"),
    Item("Staircase"),
    Item("Tall Torch"),
    Item("Ritual Mask"),
    Item("Bonfire"),
    Item("Bongo"),
    Item("Decorative Spears"),
    Item("Boulder"),
    Item("Door"),
    Item("Locked Door"),
    Item("Wicked Statue"),
    Item("Sloth Skeleton Left"),
    Item("Sloth Skeleton Middle"),
    Item("Sloth Skeleton Right"),
    Item("Standing Geode"),
    Item("Obsidian Vase"),
    Item("Crystal Chair"),
    Item("Singing Stone"),
    Item("Strange Capsule"),
    Item("Empty Capsule"),
    Item("Feed Hopper"),
    Item("Incubator"),
    Item("Heater"),
    Item("Tapper"),
    Item("Camera"),
    Item("Plush Bunny"),
    Item("Rarecrow"),
    Item("Decorative Pitcher"),
    Item("Dried Sunflower Seeds"),
    Item("Stardew Hero Trophy"),
    Item("Soda Machine"),
    Item("Barrel"),
    Item("Crate"),
    Item("Statue Of Endless Fortune"),
    Item("Mushroom Box"),
    Item("Praire King Arcade System"),
    Item("Campfire"),
    Item("Slime Incubator"),
    Item("Slime Egg Press"),
    Item("Junimo Kart Arcade System"),
    Item("Statue Of Perfection"),
    Item("Pinky Lemon"),
    Item("Foroguemon"),
    Item("Cask"),
    Item("Solid Gold Lewis"),
    Item("Auto Grabber"),
    Item("Seasonal Plant"),
    Item("Weeds"),
    Item("Stone"),
    Item("Wild Horseradish"),
    Item("Daffodil"),
    Item("Leek"),
    Item("Dandelion"),
    Item("Parsnip"),
    Item("Lumber"),
    Item("Emerald"),
    Item("Aquamarine"),
    Item("Ruby"),
    Item("Amethyst"),
    Item("Topaz"),
    Item("Jade"),
    Item("Diamond"),
    Item("Prismatic Shard"),
    Item("Cave Carrot"),
    Item("Secret Note"),
    Item("Quartz"),
    Item("Fire Quartz"),
    Item("Frozen Tear"),
    Item("Earth Crystal"),
    Item("Coconut"),
    Item("Cactus Fruit"),
    Item("Sap"),
    Item("Torch"),
    Item("Spirit Torch"),
    Item("Dwarf Scroll I", ["dwarf scroll one"]),
    Item("Dwarf Scroll II", ["dwarf scroll two"]),
    Item("Dwarf Scroll III", ["dwarf scroll three"]),
    Item("Dwarf Scroll IV", ["dwarf scroll four"]),
    Item("Chipped Amphora"),
    Item("Arrowhead"),
    Item("Lost Book"),
    Item("Ancient Doll"),
    Item("Elvish Jewelry"),
    Item("Chewing Stick"),
    Item("Ornamental Fan"),
    Item("Dinosaur Egg"),
    Item("Rare Disc"),
    Item("Ancient Sword"),
    Item("Rusty Spoon"),
    Item("Rusty Spur"),
    Item("Rusty Cog"),
    Item("Ancient Seed"),
    Item("Prehistoric Tool"),
    Item("Dried Starfish"),
    Item("Anchor"),
    Item("Glass Shards"),
    Item("Bone Flute"),
    Item("Prehistoric Handaxe"),
    Item("Dwarvish Helm"),
    Item("Dwarf Gadget"),
    Item("Ancient Drum"),
    Item("Golden Mask"),
    Item("Golden Relic"),
    Item("Strange Doll"),
    Item("Pufferfish"),
    Item("Anchovy"),
    Item("Tuna"),
    Item("Sardine"),
    Item("Bream"),
    Item("Largemouth Bass"),
    Item("Smallmouth Bass"),
    Item("Rainbow Trout"),
    Item("Salmon"),
    Item("Walleye"),
    Item("Perch"),
    Item("Carp"),
    Item("Catfish"),
    Item("Pike"),
    Item("Sunfish"),
    Item("Red Mullet"),
    Item("Herring"),
    Item("Eel"),
    Item("Octopus"),
    Item("Red Snapper"),
    Item("Squid"),
    Item("Seaweed"),
    Item("Green Algae"),
    Item("Sea Cucumber"),
    Item("Super Cucumber"),
    Item("Ghostfish"),
    Item("White Algae"),
    Item("Stonefish"),
    Item("Crimsonfish"),
    Item("Angler"),
    Item("Ice Pip"),
    Item("Lava Eel"),
    Item("Legend"),
    Item("Sandfish"),
    Item("Scorpion Carp"),
    Item("Treasure Chest"),
    Item("Joja Cola"),
    Item("Trash"),
    Item("Driftwood"),
    Item("Broken Glasses"),
    Item("Broken CD"),
    Item("Soggy Newspaper"),
    Item("Large Egg"),
    Item("Egg"),
    Item("Hay"),
    Item("Milk"),
    Item("Large Milk"),
    Item("Goat Milk"),
    Item("L. Goat Milk", ["large goat milk"]),
    Item("Green Bean"),
    Item("Cauliflower"),
    Item("Potato"),
    Item("Fried Egg"),
    Item("Omelet"),
    Item("Salad"),
    Item("Cheese Cauliflower"),
    Item("Baked Fish"),
    Item("Parsnip Soup"),
    Item("Vegetable Medley"),
    Item("Complete Breakfast"),
    Item("Fried Calamari"),
    Item("Strange Bun"),
    Item("Lucky Lunch"),
    Item("Fried Mushroom"),
    Item("Pizza"),
    Item("Bean Hotpot"),
    Item("Glazed Yams"),
    Item("Carp Surprise"),
    Item("Hashbrowns"),
    Item("Pancakes"),
    Item("Salmon Dinner"),
    Item("Fish Taco"),
    Item("Crispy Bass"),
    Item("Pepper Poppers"),
    Item("Bread"),
    Item("Tom Kha Soup"),
    Item("Trout Soup"),
    Item("Chocolate Cake"),
    Item("Pink Cake"),
    Item("Rhubarb Pie"),
    Item("Cookie"),
    Item("Spaghetti"),
    Item("Fried Eel"),
    Item("Spicy Eel"),
    Item("Sashimi"),
    Item("Maki Roll"),
    Item("Tortilla"),
    Item("Red Plate"),
    Item("Eggplant Parmesan"),
    Item("Rice Pudding"),
    Item("Ice Cream"),
    Item("Blueberry Tart"),
    Item("Autumns Bounty"),
    Item("Pumpkin Soup"),
    Item("Super Meal"),
    Item("Cranberry Sauce"),
    Item("Stuffing"),
    Item("Farmers Lunch"),
    Item("Survival Burger"),
    Item("Dish OThe Sea"),
    Item("Miners Treat"),
    Item("Roots Platter"),
    Item("Sugar"),
    Item("Wheat Flour"),
    Item("Oil"),
    Item("Garlic"),
    Item("Kale"),
    Item("Rhubarb"),
    Item("Melon"),
    Item("Tomato"),
    Item("Morel"),
    Item("Blueberry"),
    Item("Fiddlehead Fern"),
    Item("Hot Pepper"),
    Item("Wheat"),
    Item("Radish"),
    Item("Red Cabbage"),
    Item("Starfruit"),
    Item("Corn"),
    Item("Eggplant"),
    Item("Artichoke"),
    Item("Pumpkin"),
    Item("Bok Choy"),
    Item("Yam"),
    Item("Chanterelle"),
    Item("Cranberries"),
    Item("Holly"),
    Item("Beet"),
    Item("Cherry Bomb"),
    Item("Bomb"),
    Item("Mega Bomb"),
    Item("Twig"),
    Item("Salmonberry"),
    Item("Grass Starter"),
    Item("Amaranth Seeds"),
    Item("Amaranth"),
    Item("Grape Starter"),
    Item("Hops Starter"),
    Item("Pale Ale"),
    Item("Hops"),
    Item("Void Egg"),
    Item("Mayonnaise"),
    Item("Duck Mayonnaise"),
    Item("Void Mayonnaise"),
    Item("Acorn"),
    Item("Maple Seed"),
    Item("Pine Cone"),
    Item("Dwarvish Translation Guide"),
    Item("Clay"),
    Item("Copper Bar"),
    Item("Iron Bar"),
    Item("Gold Bar"),
    Item("Iridium Bar"),
    Item("Refined Quartz"),
    Item("Honey"),
    Item("Tea Set"),
    Item("Pickles"),
    Item("Jelly"),
    Item("Beer"),
    Item("Rare Seed"),
    Item("Wine"),
    Item("Energy Tonic"),
    Item("Juice"),
    Item("Muscle Remedy"),
    Item("Clam"),
    Item("Golden Pumpkin"),
    Item("Poppy"),
    Item("Copper Ore"),
    Item("Iron Ore"),
    Item("Coal"),
    Item("Gold Ore"),
    Item("Iridium Ore"),
    Item("Wood"),
    Item("Nautilus Shell"),
    Item("Coral"),
    Item("Rainbow Shell"),
    Item("Coffee"),
    Item("Spice Berry"),
    Item("Sea Urchin"),
    Item("Grape"),
    Item("Spring Onion"),
    Item("Strawberry"),
    Item("Straw Floor"),
    Item("Sweet Pea"),
    Item("Field Snack"),
    Item("Common Mushroom"),
    Item("Wood Path"),
    Item("Wild Plum"),
    Item("Gravel Path"),
    Item("Hazelnut"),
    Item("Crystal Path"),
    Item("Blackberry"),
    Item("Cobblestone Path"),
    Item("Winter Root"),
    Item("Blue Slime Egg"),
    Item("Crystal Fruit"),
    Item("Stepping Stone Path"),
    Item("Snow Yam"),
    Item("Sweet Gem Berry"),
    Item("Crocus"),
    Item("Vinegar"),
    Item("Red Mushroom"),
    Item("Sunflower"),
    Item("Purple Mushroom"),
    Item("Rice"),
    Item("Cheese"),
    Item("Fairy Seeds"),
    Item("Goat Cheese"),
    Item("Tulip Bulb"),
    Item("Cloth"),
    Item("Jazz Seeds"),
    Item("Truffle"),
    Item("Sunflower Seeds"),
    Item("Truffle Oil"),
    Item("Coffee Bean"),
    Item("Stardrop"),
    Item("Red Slime Egg"),
    Item("Purple Slime Egg"),
    Item("Wool"),
    Item("Explosive Ammo"),
    Item("Duck Egg"),
    Item("Duck Feather"),
    Item("Rabbits Foot"),
    Item("Stone Base"),
    Item("Poppy Seeds"),
    Item("Ancient Fruit"),
    Item("Spangle Seeds"),
    Item("Algae Soup"),
    Item("Pale Broth"),
    Item("Bouquet"),
    Item("Mead"),
    Item("Mermaids Pendant"),
    Item("Decorative Pot"),
    Item("Drum Block"),
    Item("Flute Block"),
    Item("Speed Gro"),
    Item("Deluxe Speed Gro"),
    Item("Parsnip Seeds"),
    Item("Bean Starter"),
    Item("Cauliflower Seeds"),
    Item("Potato Seeds"),
    Item("Garlic Seeds"),
    Item("Kale Seeds"),
    Item("Rhubarb Seeds"),
    Item("Melon Seeds"),
    Item("Tomato Seeds"),
    Item("Blueberry Seeds"),
    Item("Pepper Seeds"),
    Item("Wheat Seeds"),
    Item("Radish Seeds"),
    Item("Red Cabbage Seeds"),
    Item("Starfruit Seeds"),
    Item("Corn Seeds"),
    Item("Eggplant Seeds"),
    Item("Artichoke Seeds"),
    Item("Pumpkin Seeds"),
    Item("Bok Choy Seeds"),
    Item("Yam Seeds"),
    Item("Cranberry Seeds"),
    Item("Beet Seeds"),
    Item("Spring Seeds"),
    Item("Summer Seeds"),
    Item("Fall Seeds"),
    Item("Winter Seeds"),
    Item("Ancient Seeds"),
    Item("Geode"),
    Item("Frozen Geode"),
    Item("Magma Geode"),
    Item("Alamite"),
    Item("Bixite"),
    Item("Baryte"),
    Item("Aerinite"),
    Item("Calcite"),
    Item("Dolomite"),
    Item("Esperite"),
    Item("Fluorapatite"),
    Item("Geminite"),
    Item("Helvite"),
    Item("Jamborite"),
    Item("Jagoite"),
    Item("Kyanite"),
    Item("Lunarite"),
    Item("Malachite"),
    Item("Neptunite"),
    Item("Lemon Stone"),
    Item("Nekoite"),
    Item("Orpiment"),
    Item("Petrified Slime"),
    Item("Thunder Egg"),
    Item("Pyrite"),
    Item("Ocean Stone"),
    Item("Ghost Crystal"),
    Item("Tigerseye"),
    Item("Jasper"),
    Item("Opal"),
    Item("Fire Opal"),
    Item("Celestine"),
    Item("Marble"),
    Item("Sandstone"),
    Item("Granite"),
    Item("Basalt"),
    Item("Limestone"),
    Item("Soapstone"),
    Item("Hematite"),
    Item("Mudstone"),
    Item("Obsidian"),
    Item("Slate"),
    Item("Fairy Stone"),
    Item("Star Shards"),
    Item("Prehistoric Scapula"),
    Item("Prehistoric Tibia"),
    Item("Prehistoric Skull"),
    Item("Skeletal Hand"),
    Item("Prehistoric Rib"),
    Item("Prehistoric Vertebra"),
    Item("Skeletal Tail"),
    Item("Nautilus Fossil"),
    Item("Amphibian Fossil"),
    Item("Palm Fossil"),
    Item("Trilobite"),
    Item("Artifact Spot"),
    Item("Tulip"),
    Item("Summer Spangle"),
    Item("Fairy Rose"),
    Item("Blue Jazz"),
    Item("Plum Pudding"),
    Item("Artichoke Dip"),
    Item("Stir Fry"),
    Item("Roasted Hazelnuts"),
    Item("Pumpkin Pie"),
    Item("Radish Salad"),
    Item("Fruit Salad"),
    Item("Blackberry Cobbler"),
    Item("Cranberry Candy"),
    Item("Apple"),
    Item("Bruschetta"),
    Item("Cherry Sapling"),
    Item("Apricot Sapling"),
    Item("Orange Sapling"),
    Item("Peach Sapling"),
    Item("Pomegranate Sapling"),
    Item("Apple Sapling"),
    Item("Apricot"),
    Item("Orange"),
    Item("Peach"),
    Item("Pomegranate"),
    Item("Cherry"),
    Item("Coleslaw"),
    Item("Fiddlehead Risotto"),
    Item("Poppyseed Muffin"),
    Item("Green Slime Egg"),
    Item("Mutant Carp"),
    Item("Bug Meat"),
    Item("Bait"),
    Item("Sturgeon"),
    Item("Tiger Trout"),
    Item("Bullhead"),
    Item("Tilapia"),
    Item("Chub"),
    Item("Magnet"),
    Item("Dorado"),
    Item("Albacore"),
    Item("Shad"),
    Item("Lingcod"),
    Item("Halibut"),
    Item("Hardwood"),
    Item("Lobster"),
    Item("Crayfish"),
    Item("Crab"),
    Item("Cockle"),
    Item("Mussel"),
    Item("Shrimp"),
    Item("Snail"),
    Item("Periwinkle"),
    Item("Oyster"),
    Item("Maple Syrup"),
    Item("Oak Resin"),
    Item("Pine Tar"),
    Item("Chowder"),
    Item("Fish Stew"),
    Item("Escargot"),
    Item("Lobster Bisque"),
    Item("Maple Bar"),
    Item("Crab Cakes"),
    Item("Woodskip"),
    Item("Strawberry Seeds"),
    Item("Rotten Plant"),
    Item("Omni Geode"),
    Item("Slime"),
    Item("Bat Wing"),
    Item("Solar Essence"),
    Item("Void Essence"),
    Item("Mixed Seeds"),
    Item("Fiber"),
    Item("Life Elixir"),
    Item("Wild Bait"),
    Item("Glacierfish"),
    Item("Battery Pack"),
    Item("Lost Axe"),
    Item("Lucky Purple Shorts"),
    Item("Berry Basket"),
)

def item_commands(items):
    commands = {}
    for item in items:
        for cmd in item.commands:
            if cmd in commands:
                raise RuntimeError(f"Duplicate item {cmd}")
            commands[cmd] = item
    return commands

craftable_commands = item_commands(craftable_items)
other_item_commands = item_commands(other_items)
tool_commands = item_commands(tools)
craftable_items_choice = df.Choice("craftable_items", craftable_commands)
items_choice = df.Choice("items", {**craftable_commands, **other_item_commands, **tool_commands})
