##################################################
##
## You're viewing a file in the SMAPI mod dump, which contains a copy of every open-source SMAPI mod
## for queries and analysis.
##
## This is *not* the original file, and not necessarily the latest version.
## Source repository: https://github.com/drbirbdev/StardewValley
##
##################################################

name: Machine Translate Mod and Create Translation Files
on:
  push:
    branches:
      - none
    paths:
      - '*/i18n/**'
      - '**/i18n/default.json'

jobs:
  changes_json:
    name: Get New Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Changes Json
        id: get_new
        uses: tj-actions/changed-files@v35
        with:
          files: '**/i18n/default.json'
          json: 'true'

      - name: Set Matrix
        id: set_matrix
        if: ${{ steps.get_new.output.all_changed_files != '[]'}}
        run: |
          echo ${{ steps.get_new.outputs.all_changed_files }}
          echo "matrix={\"file\":${{ steps.get_new.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}

  translate_file:
    name: Get Translation
    runs-on: ubuntu-latest
    needs: changes_json
    if: ${{ needs.changes_json.outputs.matrix != '' }}
    strategy:
      matrix: ${{ fromJson(needs.changes_json.outputs.matrix) }}
    steps:
      - name: Get Folder
        id: parse_folder
        run: |
          echo "folder=$(echo ${{ matrix.file }} | rev | cut -c 14- | rev)" >> "$GITHUB_OUTPUT"

      - name: DeepL Translate Github Action
        uses: lyqht/deepl-translate-github-action@v2.1.1
        with:
          target_languages: de,es,fr,hu,id,it,ja,ko,pl,pt-PT,pt-BR,ru,tr,zh
          input_file_path: ${{ matrix.file }}
          output_file_name_pattern: ${{ steps.parse_folder.outputs.folder }}/{language}.json
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
