##################################################
##
## You're viewing a file in the SMAPI mod dump, which contains a copy of every open-source SMAPI mod
## for queries and analysis.
##
## This is *not* the original file, and not necessarily the latest version.
## Source repository: https://github.com/ModOrganizer2/modorganizer-basic_games
##
##################################################

name: linters

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "basic_games"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: abatilo/actions-poetry@v2
      - name: Install
        run: |
          cd basic_games
          poetry install
      - name: Lint
        run: |
          cd basic_games
          poetry run poe lint-all
