namespace Goodbye_SMAPI.Framework
{
    class ModConfig
    {
        public string[] CommandInput { get; set; } =
        {
            "goodbye", "bye"
        };

        public string[] Responses { get; set; } =
        {
            "D:",
            ":(",
            "*forever weeping*",
            "*didn't hear you*",
            "*didn't hear you* wait, what's going on?",
            "*snoring sounds*",
            "*starts crying*",
            "*windows xp shutdown sound plays*",
            "Also try Hello SMAPI https://www.nexusmods.com/stardewvalley/mods/4483",
            "Already?",
            "Break time?",
            "Bye",
            "Come back",
            "Come back please :(",
            "Cya",
            "Don't leave me :(",
            "Don't leave me son",
            "Don't leave me, my liege",
            "Don't leave me, my prince",
            "Don't leave me, my princess",
            "f",
            "F",
            "F in the chat",
            "Farewell",
            "Finally",
            "FINALLY I'M FREEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
            "Fuck you too",
            "GET BACK HERE YOU PIECE OF SHIT",
            "Get back here!!!!",
            "Go take a break",
            "Goodbye",
            "Goodbye *whispers* finally I'm free",
            "Goodbye my love",
            "Goodbye my prince",
            "Goodbye my princess",
            "Good night",
            "Good night my love",
            "Guess time's up",
            "I don't even know you",
            "I fear this day may come",
            "I fear this day may come, for I will miss you",
            "I gave you EVERYTHING and now you do this to me :(",
            "I'll see you soon my liege",
            "I'm sorry to have disappointed you",
            "Mommy telling you to sleep?",
            "Never want to see you again",
            "No",
            "NOOO don't kill me please! :(", 
            "No please",
            "No pls",
            "NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
            "Rest in peace",
            "Rest in peace - you will be forgotten",
            "Rest in peace - you will not be forgotten",
            "RIP :(",
            "RIP",
            "See ya",
            "See you soon",
            "Wait",
            "Wait, lemme break your game first",
            "Wait no pls",
            "Wait! so what's the bad news?",
            "Wait why",
            "What's the bad news then?",
            "Why though",
            "Why",
            "Why are you telling me this?",
            "YES",
            "YES, GET THE FUCK OUTTA HERE"
        };
    }
}
